/* automatically generated by rust-bindgen 0.59.1 */

extern "C" {
    #[doc = " Constructs the suffix array of a given string."]
    #[doc = " @param T [0..n-1] The input string."]
    #[doc = " @param SA [0..n-1] The output array of suffixes."]
    #[doc = " @param n The length of the given string."]
    #[doc = " @return 0 if no error occurred, -1 or -2 otherwise."]
    pub fn libsais(
        T: *const ::std::os::raw::c_uchar,
        SA: *mut ::std::os::raw::c_int,
        n: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
